//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvPHelper.Core.Achievements {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class AchievementList : global::System.Configuration.ApplicationSettingsBase {
        
        private static AchievementList defaultInstance = ((AchievementList)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AchievementList())));
        
        public static AchievementList Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WildSenko {
            get {
                return ((bool)(this["WildSenko"]));
            }
            set {
                this["WildSenko"] = value;
            }
        }
    }
}
